
CXXFLAGS = -g -Wall -Og

infectionProject: Board.o conio.o Human.o Programmer.o main.o Board.h conio.h Human.h Programmer.h 
	g++ -o infectionProject Board.o conio.o Human.o Programmer.o main.o 


	


clean:
	rm -f *.o a.out infectionProject 






